apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations: 
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/ingress: internal-and-cloud-load-balancing 
  name: ${SERVICE_NAME}
spec:
  template:
    metadata:      
      name: ${SERVICE_NAME}-${REVISION_TAG}-release
      annotations:
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/minScale: '3'
        autoscaling.knative.dev/maxScale: '100'
      labels: 
        region: ${REGION}
        app_code: ${APP_CODE}
        classification: ${CLASSIFICATION}
        cost_id: ${COST_ID}
        department_id: ${DEPARTMENT_ID}
        hca_project_id: ${HCA_PROJECT_ID}
        tco_id: ${TCO_ID}
        app_environment: ${ENVIRONMENT}
    spec:
      containerConcurrency: 80
      serviceAccountName: ${CLOUD_RUN_SA}
      containers:
      - image: ${CONTAINER_IMAGE}
        name: ${SERVICE_NAME}
        ports: 
        - name: http1
          containerPort: 80
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
        - name: DATABASE_HOST 
          valueFrom:
            secretKeyRef:
              name: DATABASE_HOST
              key: "1"
        - name: DATABASE_NAME 
          valueFrom:
            secretKeyRef:
              name: DATABASE_NAME 
              key: "1"         
        - name: DATABASE_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: DATABASE_USERNAME
              key: "1"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: DATABASE_PASSWORD 
              key: "1"
  traffic: 
  - latestRevision: true
    percent: 100