name: Reusable Liquibase Publishing Workflow

on:
  workflow_call:
    inputs:
      RUNNER:
        description: "The Github runner platform (runs-on) value for the jobs"
        type: string
        required: true
      environment:
        description: "The Github environment to run the workflow with"
        type: string
        required: true
      URL:
        description: "The Jdbc url for liquibase to establish connection with"
        type: string
        required: true
      GOOGLE_CLOUD_PROJECT:
        description: "Name of the GCP Project"
        type: string
        required: true
      SQL_LOG_LEVEL:
        description: "The SQL Log Level setting for Liquibase"
        type: string
        required: true
      LOG_LEVEL:
        description: "Log Level setting for Liquibase"
        type: string
        required: true
    secrets:
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      SERVICE_ACCOUNT:
        required: true
      USERNAME:
        required: true

jobs:
  liquibase:
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.RUNNER }}
    timeout-minutes: 360
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: write
      actions: read
      security-events: write

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v2'
      with:
        secrets: |- 
          SQL_CONNECTION:${{inputs.GOOGLE_CLOUD_PROJECT}}/SQL_INSTANCE_CONNECTION_NAME

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Enable cloud SQL proxy to temp instance
      run: |
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.7.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        nohup ./cloud-sql-proxy --auto-iam-authn ${{ steps.secrets.outputs.SQL_CONNECTION }} > cloud-sql-proxy.out 2> cloud-sql-proxy.err < /dev/null &
        echo $!
        echo CLOUD_SQL_PROXY_PID=$(echo $!) >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download and Install liquibase
      run: |
        curl -L https://github.com/liquibase/liquibase/releases/download/v4.28.0/liquibase-4.28.0.zip --output liquibase-4.28.0.zip
        unzip -o -d liquibase liquibase-4.28.0.zip

    - name: Liquibase Status
      run: |
        ./liquibase/liquibase --defaultsFile=./liquibase.properties --log-level ${{inputs.LOG_LEVEL}} --sql-log-level ${{inputs.SQL_LOG_LEVEL}} --url ${{ inputs.URL }} --username ${{ secrets.USERNAME }} status --verbose

    - name: Liquibase Print SQL
      run: |
        ./liquibase/liquibase --defaultsFile=./liquibase.properties --log-level ${{inputs.LOG_LEVEL}} --sql-log-level ${{inputs.SQL_LOG_LEVEL}} --url ${{ inputs.URL }} --username ${{ secrets.USERNAME }} --output-file=./artifacts/update-sql.sql update-sql

    - name: Set Timestamp
      run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV

    - name: Upload SQL statements
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ inputs.environment }}-${{ env.TIMESTAMP }}
        path: ./artifacts/update-sql.sql

    - name: Liquibase Update
      run: |
        ./liquibase/liquibase --defaultsFile=./liquibase.properties --log-level ${{inputs.LOG_LEVEL}} --sql-log-level ${{inputs.SQL_LOG_LEVEL}} --url ${{ inputs.URL }} --username ${{ secrets.USERNAME }} update
