name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-production:
    name: Liquibase plan and Update on production
    uses: ./.github/workflows/liquibase-release.yml
    secrets:
      URL: ${{ secrets.URL }}
      USERNAME: ${{ secrets.USERNAME }}
    with:
      WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ vars.SERVICE_ACCOUNT }}
      GOOGLE_CLOUD_PROJECT : ${{ vars.GOOGLE_CLOUD_PROJECT }}
      SQL_LOG_LEVEL: ${{ vars.SQL_LOG_LEVEL }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
