name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  plan-production:
    name: Prod Plan - Liquibase plan and Update
    uses: ./.github/workflows/liquibase-ci.yml
    secrets:
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      USERNAME: ${{ secrets.USERNAME }}
    with:
      environment: 'prod-plan'
      runner: 'ubuntu-latest'

  deploy-production:
    name: Prod Deploy - Liquibase plan and Update on production
    uses: ./.github/workflows/liquibase-release.yml
    secrets:
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      USERNAME: ${{ secrets.USERNAME }}
    with:
      environment: 'prod'
      runner: 'ubuntu-latest'
